{% set version = "2.3.1" %}

package:
  name: charls
  version: {{ version }}

source:
  url: https://github.com/team-charls/charls/archive/{{ version }}.tar.gz
  sha256: d274107538c70abfce5459c40ed1ec5ef354193ad9e2c55de6293ca358d52e97

build:
  skip: true  # [win and vc<14]
  number: 0
  run_exports:
    # Seems like things change with minor revision (2.0 - 2.1) had many file
    # name changes
    - {{ pin_subpackage('charls', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libcharls${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/charls/charls.h       # [unix]
    - if not exist %LIBRARY_LIB%\\charls-2-x64.lib exit 1       # [win]
    - if not exist %LIBRARY_BIN%\\charls-2-x64.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\\charls\\charls.h exit 1       # [win]

about:
  home: https://github.com/team-charls/charls
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: CharLS is a C++ implementation of the JPEG-LS standard for lossless and near-lossless image compression and decompression. JPEG-LS is a low-complexity image compression standard that matches JPEG 2000 compression ratios.

extra:
  recipe-maintainers:
    - hmaarrfk
