build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: 
      oatYZI7jwzB0csnf0+n7ZqKj0DzuFopPM63JWyRHLaX7DNE9pKlkzL11qV1MhqU35CKwbvKlf8B41S2bQFMSyFW9ZCPzu7kAmqxYVf07K7GXWV/JZHy10ltTP//EEzM+Vble4SlDu+7ietQXKsl18PfWzMVx6/IsDtaYX+SkHtSzV2p+vx78KymOMV/6fatkImD6b7ZCpXbCmR8ZLSqbKb2Q6EUTGyPIobhNkT7fqZus/hqNtaNGjDM2y4B2wjsc3/lHApuBTXs4axkWbPwUoO0/5MkuXTiMvQz95ZP2mj6oCBuD6LOaH5nIZVHtapE3HNsK4YKuCX+HpVLT2IXmF+e/gf9IS63Mdv2xIIIAQd2JsnwFn9nDj4chgXnPd50AI59DbSIpM8/FcrDVjLNCAvcY+x635jCMnjjQqt1dvCO15ouVe6cjtpyJbPUmEiIMRSDkq7vdRTQgjNUPLUzljmE7YsEFodfZzD/i2oDXo/GT5YFrexBxacETEIJz8iD8MLdaCxdM5CyEMtiE6NrxPdTbmIc/79hR6H7EjwHfZjJ7cnFAkOw6PvY97wVsS4zEQLzR4JfDyrHaQRGCatokxvjRo+xeQactedQVxdNiefjQDFU3cungDsqVrd50/dzy/3iW9l06TnOM3maXZMYYzter7NnrhhX5N+4CotL/r8Q=}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
